version: '3.8'

services:
  qwen3-tts-api:
    image: mosstnslv/qwen-tts-service:0.0.1
    container_name: qwen3-tts-api
    runtime: nvidia
    ports:
      - "8188:8188"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HF_HOME=/app/models
    volumes:
      - qwen3-models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  qwen3-models:
